### PR TITLE
Swap out bufio.Scanner for bufio.Reader

### LINKED ISSUE #11: Large lines (>64k) cause error with bufio.Scanner
[Known limitation with Scanner, with a standard workaround.
](https://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca)

Large JSON objects with the newline-delimited JSON input caused me to have this issue, and doesn't seem like a rare use case for this library.

### PR DESCRIPTION
**Pull request by bvandersloot**
Fix #11

### CODE REVIEW

**Comment by zakird** [comment]
I'm not sure if I understand the intuition here behind why Readln was added here. Is there any reason to not just use `ReadString('\n')` or `ReadBytes('\n')?

**Comment by bvandersloot** [comment]
I had not seen `ReadString`! Not sure how I missed it!

**Comment by zakird** [comment]
Does this miss the last line? Seems like if err == eof could be weird. Might he worth testing once.

**Comment by bvandersloot** [comment]
Tested- it catches the last line. The last line is returned with `err == nil`, then the loop breaks with an EOF error in the normal case.

**Pull request merged**
